version: "3"
services:
  php-apache:
    build: .
    ports:
      - "80:80"
    links:
      - dbmysql 
    volumes:
      - ./app:/var/www/html

  dbmysql:
    image: mariadb
    volumes:
      - './data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"